@startuml

class UserMapper{
<<static>>
+ User login(String email, String password, ConnectionPool connectionPool) throws DatabaseException
+ User createUser(String name, String email, String password, ConnectionPool connectionPool) throws DatabaseException
+ User getUserByID (int userID, ConnectionPool connectionPool) throws DatabaseException
+ List<User> getAllUsers(ConnectionPool, connectionPool) throws DatabaseException
}

class OrderMapper{
+ Order createOrder (Carport carport, int UserID, ConnectionPool connectionPool) throws DatabaseException
+ Order getOrderByOrderID(int orderID, ConnectionPool connectionPool) throws DatabaseException
+ List<Order> getAllOrders(ConnectionPool connectionPool) throws DatabaseException
+ List<Order> getAllOrdersByID(Int userID, ConnectionPool connectionPool) throws DatabaseException
+ void editOrder (int orderID, ConnectionPool connectionPool) throws DatabaseException
+ void updateApproveOrder (int orderID, ConnectionPool connectionPool) throws DatabaseException
+ void updateOrderPayment (int orderID, ConnectionPool connectionPool) throws DatabaseException
+ void deleteOrder ( int orderID, ConnectionPool connectionPool) throws DatabaseException
}

class MaterialMapper{
void materialPriceUpdate (int materialID, double price, ConnectionPool connectionPool) throws DatabaseException
void materialAdd (String name, double price,String materialTypeDescription, String materialDescription, String functionDescription, ConnectionPool connectionPool) throws DatabaseException
void materialDelte (int materialID, ConnectionPool connectionPool) throws DatabaseException
List<Rafter> rafters (ConnectionPool connectionPool) throws DatabaseException
List<Post> posts (ConnectionPool connectionPool) throws DatabaseException
List<Purlin> purlins (ConnectionPool connectionPool) throws DatabaseException
list<Materials> partList (int OrderId, rafters, posts, purlins, ConnectionPool connectionPool) throws DatabaseException
}

class ConnectionPool{
- HikariDataSource ds
- String USER
- String PASSWORD
- STRING URL
+ ConnectionPool(String USER, String PASSWORD, String URL)
+ void close()
}


@enduml